### PR TITLE
Create Homepage and add new staking option

### PR DESCRIPTION
**Pull request by markii1607**
Created a homepage for the staking and added a new staking option, **"Stake OWN, Earn Mustachio Marauder"**.

### CODE REVIEW

**Comment by bernardhistorillo** [comment]
Lavet!

**Comment by bernardhistorillo** [comment]
We ask for Your guidance as we merge this branch to production. Amen.

**Comment by markii1607** [comment]
Amen!

**Comment by bernardhistorillo** [comment]
May conflicts Mark

**Comment by markii1607** [comment]
overwrite mo langs su sa main

**Comment by bernardhistorillo** [comment]
Ikaw na magmerge, I give you the power.

**Pull request closed without merging**
